import Ember from 'ember';
import controllerSetup from '../code-highlights/home/controller-setup';
import standardSelect from '../code-highlights/home/standard-select';
import multipleSelect from '../code-highlights/home/multiple-select';
import optgroupSelect from '../code-highlights/home/optgroup-select';
import actionSelect from '../code-highlights/home/action-select-hbs';
import actionSelectController from '../code-highlights/home/action-select-controller';

export default Ember.Controller.extend({
  controllerSetupCode: controllerSetup,
  standardSelectCode: standardSelect,
  multipleSelectCode: multipleSelect,
  optgroupSelectCode: optgroupSelect,
  actionSelectCode: actionSelect,
  actionSelectControllerCode: actionSelectController,
  singleSelectValue: null,
  multipleSelectValue: null,
  optgroupSelectValue: null,
  actionMessage: null,
  actions: {
    onSelectionChanged: function(selectedValue) {
      this.set('actionMessage', 'You selected ' + selectedValue + '!');
    }
  },
  countries: [
    {name: 'United States', code: 'US', group: 'Group #1'},
    {name: 'United Kingdom', code: 'GB', group: 'Group #1'},
    {name: 'Afghanistan', code: 'AF', group: 'Group #1'},
    {name: 'Åland Islands', code: 'AX', group: 'Group #1'},
    {name: 'Albania', code: 'AL', group: 'Group #1'},
    {name: 'Algeria', code: 'DZ', group: 'Group #1'},
    {name: 'American Samoa', code: 'AS', group: 'Group #1'},
    {name: 'AndorrA', code: 'AD', group: 'Group #1'},
    {name: 'Angola', code: 'AO', group: 'Group #1'},
    {name: 'Anguilla', code: 'AI', group: 'Group #1'},
    {name: 'Antarctica', code: 'AQ', group: 'Group #1'},
    {name: 'Antigua and Barbuda', code: 'AG', group: 'Group #1'},
    {name: 'Argentina', code: 'AR', group: 'Group #1'},
    {name: 'Armenia', code: 'AM', group: 'Group #1'},
    {name: 'Aruba', code: 'AW', group: 'Group #1'},
    {name: 'Australia', code: 'AU', group: 'Group #1'},
    {name: 'Austria', code: 'AT', group: 'Group #1'},
    {name: 'Azerbaijan', code: 'AZ', group: 'Group #1'},
    {name: 'Bahamas', code: 'BS', group: 'Group #1'},
    {name: 'Bahrain', code: 'BH', group: 'Group #1'},
    {name: 'Bangladesh', code: 'BD', group: 'Group #1'},
    {name: 'Barbados', code: 'BB', group: 'Group #1'},
    {name: 'Belarus', code: 'BY', group: 'Group #1'},
    {name: 'Belgium', code: 'BE', group: 'Group #1'},
    {name: 'Belize', code: 'BZ', group: 'Group #1'},
    {name: 'Benin', code: 'BJ', group: 'Group #1'},
    {name: 'Bermuda', code: 'BM', group: 'Group #1'},
    {name: 'Bhutan', code: 'BT', group: 'Group #1'},
    {name: 'Bolivia', code: 'BO', group: 'Group #1'},
    {name: 'Bosnia and Herzegovina', code: 'BA', group: 'Group #1'},
    {name: 'Botswana', code: 'BW', group: 'Group #1'},
    {name: 'Bouvet Island', code: 'BV', group: 'Group #1'},
    {name: 'Brazil', code: 'BR', group: 'Group #1'},
    {name: 'British Indian Ocean Territory', code: 'IO', group: 'Group #1'},
    {name: 'Brunei Darussalam', code: 'BN', group: 'Group #1'},
    {name: 'Bulgaria', code: 'BG', group: 'Group #1'},
    {name: 'Burkina Faso', code: 'BF', group: 'Group #1'},
    {name: 'Burundi', code: 'BI', group: 'Group #2'},
    {name: 'Cambodia', code: 'KH', group: 'Group #2'},
    {name: 'Cameroon', code: 'CM', group: 'Group #2'},
    {name: 'Canada', code: 'CA', group: 'Group #2'},
    {name: 'Cape Verde', code: 'CV', group: 'Group #2'},
    {name: 'Cayman Islands', code: 'KY', group: 'Group #2'},
    {name: 'Central African Republic', code: 'CF', group: 'Group #2'},
    {name: 'Chad', code: 'TD', group: 'Group #2'},
    {name: 'Chile', code: 'CL', group: 'Group #2'},
    {name: 'China', code: 'CN', group: 'Group #2'},
    {name: 'Christmas Island', code: 'CX', group: 'Group #2'},
    {name: 'Cocos (Keeling) Islands', code: 'CC', group: 'Group #2'},
    {name: 'Colombia', code: 'CO', group: 'Group #2'},
    {name: 'Comoros', code: 'KM', group: 'Group #2'},
    {name: 'Congo', code: 'CG', group: 'Group #2'},
    {name: 'Congo, The Democratic Republic of the', code: 'CD', group: 'Group #2'},
    {name: 'Cook Islands', code: 'CK', group: 'Group #2'},
    {name: 'Costa Rica', code: 'CR', group: 'Group #2'},
    {name: 'Cote D\'Ivoire', code: 'CI', group: 'Group #2'},
    {name: 'Croatia', code: 'HR', group: 'Group #3'},
    {name: 'Cuba', code: 'CU', group: 'Group #3'},
    {name: 'Cyprus', code: 'CY', group: 'Group #3'},
    {name: 'Czech Republic', code: 'CZ', group: 'Group #3'},
    {name: 'Denmark', code: 'DK', group: 'Group #3'},
    {name: 'Djibouti', code: 'DJ', group: 'Group #3'},
    {name: 'Dominica', code: 'DM', group: 'Group #3'},
    {name: 'Dominican Republic', code: 'DO', group: 'Group #3'},
    {name: 'Ecuador', code: 'EC', group: 'Group #3'},
    {name: 'Egypt', code: 'EG', group: 'Group #3'},
    {name: 'El Salvador', code: 'SV', group: 'Group #3'},
    {name: 'Equatorial Guinea', code: 'GQ', group: 'Group #3'},
    {name: 'Eritrea', code: 'ER', group: 'Group #3'},
    {name: 'Estonia', code: 'EE', group: 'Group #3'},
    {name: 'Ethiopia', code: 'ET', group: 'Group #3'},
    {name: 'Falkland Islands (Malvinas)', code: 'FK', group: 'Group #3'},
    {name: 'Faroe Islands', code: 'FO', group: 'Group #3'},
    {name: 'Fiji', code: 'FJ', group: 'Group #3'},
    {name: 'Finland', code: 'FI', group: 'Group #3'},
    {name: 'France', code: 'FR', group: 'Group #3'},
    {name: 'French Guiana', code: 'GF', group: 'Group #3'},
    {name: 'French Polynesia', code: 'PF', group: 'Group #3'},
    {name: 'French Southern Territories', code: 'TF', group: 'Group #3'},
    {name: 'Gabon', code: 'GA', group: 'Group #3'},
    {name: 'Gambia', code: 'GM', group: 'Group #3'},
    {name: 'Georgia', code: 'GE', group: 'Group #3'},
    {name: 'Germany', code: 'DE', group: 'Group #3'},
    {name: 'Ghana', code: 'GH', group: 'Group #3'},
    {name: 'Gibraltar', code: 'GI', group: 'Group #3'},
    {name: 'Greece', code: 'GR', group: 'Group #3'},
    {name: 'Greenland', code: 'GL', group: 'Group #3'},
    {name: 'Grenada', code: 'GD', group: 'Group #3'},
    {name: 'Guadeloupe', code: 'GP', group: 'Group #3'},
    {name: 'Guam', code: 'GU', group: 'Group #3'},
    {name: 'Guatemala', code: 'GT', group: 'Group #3'},
    {name: 'Guernsey', code: 'GG', group: 'Group #3'},
    {name: 'Guinea', code: 'GN', group: 'Group #3'},
    {name: 'Guinea-Bissau', code: 'GW', group: 'Group #3'},
    {name: 'Guyana', code: 'GY', group: 'Group #3'},
    {name: 'Haiti', code: 'HT', group: 'Group #3'},
    {name: 'Heard Island and Mcdonald Islands', code: 'HM', group: 'Group #3'},
    {name: 'Holy See (Vatican City State)', code: 'VA', group: 'Group #3'},
    {name: 'Honduras', code: 'HN', group: 'Group #3'},
    {name: 'Hong Kong', code: 'HK', group: 'Group #3'},
    {name: 'Hungary', code: 'HU', group: 'Group #3'},
    {name: 'Iceland', code: 'IS', group: 'Group #3'},
    {name: 'India', code: 'IN', group: 'Group #3'},
    {name: 'Indonesia', code: 'ID', group: 'Group #3'},
    {name: 'Iran, Islamic Republic Of', code: 'IR', group: 'Group #3'},
    {name: 'Iraq', code: 'IQ', group: 'Group #3'},
    {name: 'Ireland', code: 'IE', group: 'Group #3'},
    {name: 'Isle of Man', code: 'IM', group: 'Group #3'},
    {name: 'Israel', code: 'IL', group: 'Group #3'},
    {name: 'Italy', code: 'IT', group: 'Group #3'},
    {name: 'Jamaica', code: 'JM', group: 'Group #3'},
    {name: 'Japan', code: 'JP', group: 'Group #3'},
    {name: 'Jersey', code: 'JE', group: 'Group #3'},
    {name: 'Jordan', code: 'JO', group: 'Group #3'},
    {name: 'Kazakhstan', code: 'KZ', group: 'Group #3'},
    {name: 'Kenya', code: 'KE', group: 'Group #3'},
    {name: 'Kiribati', code: 'KI', group: 'Group #3'},
    {name: 'Korea, Democratic People\'S Republic of', code: 'KP', group: 'Group #3'},
    {name: 'Korea, Republic of', code: 'KR', group: 'Group #3'},
    {name: 'Kuwait', code: 'KW', group: 'Group #3'},
    {name: 'Kyrgyzstan', code: 'KG', group: 'Group #3'},
    {name: 'Lao People\'S Democratic Republic', code: 'LA', group: 'Group #3'},
    {name: 'Latvia', code: 'LV', group: 'Group #3'},
    {name: 'Lebanon', code: 'LB', group: 'Group #3'},
    {name: 'Lesotho', code: 'LS', group: 'Group #3'},
    {name: 'Liberia', code: 'LR', group: 'Group #3'},
    {name: 'Libyan Arab Jamahiriya', code: 'LY', group: 'Group #3'},
    {name: 'Liechtenstein', code: 'LI', group: 'Group #3'},
    {name: 'Lithuania', code: 'LT', group: 'Group #3'},
    {name: 'Luxembourg', code: 'LU', group: 'Group #3'},
    {name: 'Macao', code: 'MO', group: 'Group #3'},
    {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', group: 'Group #4'},
    {name: 'Madagascar', code: 'MG', group: 'Group #4'},
    {name: 'Malawi', code: 'MW', group: 'Group #4'},
    {name: 'Malaysia', code: 'MY', group: 'Group #4'},
    {name: 'Maldives', code: 'MV', group: 'Group #4'},
    {name: 'Mali', code: 'ML', group: 'Group #4'},
    {name: 'Malta', code: 'MT', group: 'Group #4'},
    {name: 'Marshall Islands', code: 'MH', group: 'Group #4'},
    {name: 'Martinique', code: 'MQ', group: 'Group #4'},
    {name: 'Mauritania', code: 'MR', group: 'Group #4'},
    {name: 'Mauritius', code: 'MU', group: 'Group #4'},
    {name: 'Mayotte', code: 'YT', group: 'Group #4'},
    {name: 'Mexico', code: 'MX', group: 'Group #4'},
    {name: 'Micronesia, Federated States of', code: 'FM', group: 'Group #4'},
    {name: 'Moldova, Republic of', code: 'MD', group: 'Group #4'},
    {name: 'Monaco', code: 'MC', group: 'Group #4'},
    {name: 'Mongolia', code: 'MN', group: 'Group #4'},
    {name: 'Montserrat', code: 'MS', group: 'Group #4'},
    {name: 'Morocco', code: 'MA', group: 'Group #4'},
    {name: 'Mozambique', code: 'MZ', group: 'Group #4'},
    {name: 'Myanmar', code: 'MM', group: 'Group #4'},
    {name: 'Namibia', code: 'NA', group: 'Group #4'},
    {name: 'Nauru', code: 'NR', group: 'Group #4'},
    {name: 'Nepal', code: 'NP', group: 'Group #4'},
    {name: 'Netherlands', code: 'NL', group: 'Group #4'},
    {name: 'Netherlands Antilles', code: 'AN', group: 'Group #4'},
    {name: 'New Caledonia', code: 'NC', group: 'Group #4'},
    {name: 'New Zealand', code: 'NZ', group: 'Group #4'},
    {name: 'Nicaragua', code: 'NI', group: 'Group #4'},
    {name: 'Niger', code: 'NE', group: 'Group #4'},
    {name: 'Nigeria', code: 'NG', group: 'Group #4'},
    {name: 'Niue', code: 'NU', group: 'Group #4'},
    {name: 'Norfolk Island', code: 'NF', group: 'Group #4'},
    {name: 'Northern Mariana Islands', code: 'MP', group: 'Group #4'},
    {name: 'Norway', code: 'NO', group: 'Group #4'},
    {name: 'Oman', code: 'OM', group: 'Group #4'},
    {name: 'Pakistan', code: 'PK', group: 'Group #4'},
    {name: 'Palau', code: 'PW', group: 'Group #4'},
    {name: 'Palestinian Territory, Occupied', code: 'PS', group: 'Group #4'},
    {name: 'Panama', code: 'PA', group: 'Group #4'},
    {name: 'Papua New Guinea', code: 'PG', group: 'Group #4'},
    {name: 'Paraguay', code: 'PY', group: 'Group #4'},
    {name: 'Peru', code: 'PE', group: 'Group #4'},
    {name: 'Philippines', code: 'PH', group: 'Group #4'},
    {name: 'Pitcairn', code: 'PN', group: 'Group #4'},
    {name: 'Poland', code: 'PL', group: 'Group #4'},
    {name: 'Portugal', code: 'PT', group: 'Group #4'},
    {name: 'Puerto Rico', code: 'PR', group: 'Group #4'},
    {name: 'Qatar', code: 'QA', group: 'Group #4'},
    {name: 'Reunion', code: 'RE', group: 'Group #4'},
    {name: 'Romania', code: 'RO', group: 'Group #4'},
    {name: 'Russian Federation', code: 'RU', group: 'Group #4'},
    {name: 'RWANDA', code: 'RW', group: 'Group #4'},
    {name: 'Saint Helena', code: 'SH', group: 'Group #4'},
    {name: 'Saint Kitts and Nevis', code: 'KN', group: 'Group #4'},
    {name: 'Saint Lucia', code: 'LC', group: 'Group #4'},
    {name: 'Saint Pierre and Miquelon', code: 'PM', group: 'Group #4'},
    {name: 'Saint Vincent and the Grenadines', code: 'VC', group: 'Group #4'},
    {name: 'Samoa', code: 'WS', group: 'Group #4'},
    {name: 'San Marino', code: 'SM', group: 'Group #4'},
    {name: 'Sao Tome and Principe', code: 'ST', group: 'Group #4'},
    {name: 'Saudi Arabia', code: 'SA', group: 'Group #4'},
    {name: 'Senegal', code: 'SN', group: 'Group #4'},
    {name: 'Serbia and Montenegro', code: 'CS', group: 'Group #4'},
    {name: 'Seychelles', code: 'SC', group: 'Group #4'},
    {name: 'Sierra Leone', code: 'SL', group: 'Group #4'},
    {name: 'Singapore', code: 'SG', group: 'Group #4'},
    {name: 'Slovakia', code: 'SK', group: 'Group #4'},
    {name: 'Slovenia', code: 'SI', group: 'Group #4'},
    {name: 'Solomon Islands', code: 'SB', group: 'Group #4'},
    {name: 'Somalia', code: 'SO', group: 'Group #4'},
    {name: 'South Africa', code: 'ZA', group: 'Group #4'},
    {name: 'South Georgia and the South Sandwich Islands', code: 'GS', group: 'Group #4'},
    {name: 'Spain', code: 'ES', group: 'Group #4'},
    {name: 'Sri Lanka', code: 'LK', group: 'Group #4'},
    {name: 'Sudan', code: 'SD', group: 'Group #4'},
    {name: 'Suriname', code: 'SR', group: 'Group #4'},
    {name: 'Svalbard and Jan Mayen', code: 'SJ', group: 'Group #4'},
    {name: 'Swaziland', code: 'SZ', group: 'Group #4'},
    {name: 'Sweden', code: 'SE', group: 'Group #4'},
    {name: 'Switzerland', code: 'CH', group: 'Group #4'},
    {name: 'Syrian Arab Republic', code: 'SY', group: 'Group #4'},
    {name: 'Taiwan, Province of China', code: 'TW', group: 'Group #4'},
    {name: 'Tajikistan', code: 'TJ', group: 'Group #4'},
    {name: 'Tanzania, United Republic of', code: 'TZ', group: 'Group #4'},
    {name: 'Thailand', code: 'TH', group: 'Group #4'},
    {name: 'Timor-Leste', code: 'TL', group: 'Group #4'},
    {name: 'Togo', code: 'TG', group: 'Group #4'},
    {name: 'Tokelau', code: 'TK', group: 'Group #4'},
    {name: 'Tonga', code: 'TO', group: 'Group #4'},
    {name: 'Trinidad and Tobago', code: 'TT', group: 'Group #4'},
    {name: 'Tunisia', code: 'TN', group: 'Group #4'},
    {name: 'Turkey', code: 'TR', group: 'Group #4'},
    {name: 'Turkmenistan', code: 'TM', group: 'Group #4'},
    {name: 'Turks and Caicos Islands', code: 'TC', group: 'Group #4'},
    {name: 'Tuvalu', code: 'TV', group: 'Group #4'},
    {name: 'Uganda', code: 'UG', group: 'Group #4'},
    {name: 'Ukraine', code: 'UA', group: 'Group #4'},
    {name: 'United Arab Emirates', code: 'AE', group: 'Group #4'},
    {name: 'United States Minor Outlying Islands', code: 'UM', group: 'Group #4'},
    {name: 'Uruguay', code: 'UY', group: 'Group #4'},
    {name: 'Uzbekistan', code: 'UZ', group: 'Group #4'},
    {name: 'Vanuatu', code: 'VU', group: 'Group #4'},
    {name: 'Venezuela', code: 'VE', group: 'Group #4'},
    {name: 'Viet Nam', code: 'VN', group: 'Group #4'},
    {name: 'Virgin Islands, British', code: 'VG', group: 'Group #4'},
    {name: 'Virgin Islands, U.S.', code: 'VI', group: 'Group #4'},
    {name: 'Wallis and Futuna', code: 'WF', group: 'Group #4'},
    {name: 'Western Sahara', code: 'EH', group: 'Group #4'},
    {name: 'Yemen', code: 'YE', group: 'Group #4'},
    {name: 'Zambia', code: 'ZM', group: 'Group #4'},
    {name: 'Zimbabwe', code: 'ZW', group: 'Group #4'}
  ]
});
